#!/usr/bin/env sh

cd backend

# PHPStan
./vendor/bin/phpstan analyse
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com PHPSTAN. Arrume antes de continuar...";
    exit 1;
fi;

# Testes
php artisan test --parallel
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com algum teste. Arrume antes de continuar...";
    exit 1;
fi;

# Pint nos arquivos staged
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "\.php$") || true
for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}" > /dev/null 2>&1;
    git add "${FILE}";
done;

exit 0;